FROM rust:alpine3.20

RUN apk add --no-cache build-base musl-dev openssl-dev openssl

WORKDIR /app

COPY Cargo.toml Cargo.lock ./

RUN mkdir src && \
	echo "fn main() {}" > src/main.rs && \
	cargo fetch 

COPY ./src ./src

RUN cargo build --release

RUN adduser -D -S rust-san && \
    mkdir -p /app/bin && \
    cp /app/target/release/WIK-DPS-TP01 /app/bin/WIK-DPS-TP01 && \
    chown -R rust-san /app/bin 

USER rust-san

CMD ["/app/bin/WIK-DPS-TP01"]