FROM node:18 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

FROM node:18-slim AS production
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package*.json ./
COPY --from=build /app/dist ./dist
COPY --from=build /app/public ./public
COPY --from=build /app/*.js ./
COPY --from=build /app/*.json ./

EXPOSE 3000

CMD ["npm", "start"]
